// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM1l42u0XIFh0NC5gBQHLi3dPUQKkETdg',
    appId: '1:286957351892:web:4baa864ff64d2bee649c41',
    messagingSenderId: '286957351892',
    projectId: 'chat-with-firebase-83b97',
    authDomain: 'chat-with-firebase-83b97.firebaseapp.com',
    storageBucket: 'chat-with-firebase-83b97.appspot.com',
    measurementId: 'G-7LYEBMNVMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-5ofGECl347gBchuLgGYLW_c90QPhQwY',
    appId: '1:286957351892:android:2e79b00de80460f7649c41',
    messagingSenderId: '286957351892',
    projectId: 'chat-with-firebase-83b97',
    storageBucket: 'chat-with-firebase-83b97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD39etH3tAgSwm8l7CRALRZbOGUd1vsAuQ',
    appId: '1:286957351892:ios:c6531905f01ffb39649c41',
    messagingSenderId: '286957351892',
    projectId: 'chat-with-firebase-83b97',
    storageBucket: 'chat-with-firebase-83b97.appspot.com',
    iosBundleId: 'com.example.mobileAppDecubitus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD39etH3tAgSwm8l7CRALRZbOGUd1vsAuQ',
    appId: '1:286957351892:ios:c6531905f01ffb39649c41',
    messagingSenderId: '286957351892',
    projectId: 'chat-with-firebase-83b97',
    storageBucket: 'chat-with-firebase-83b97.appspot.com',
    iosBundleId: 'com.example.mobileAppDecubitus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM1l42u0XIFh0NC5gBQHLi3dPUQKkETdg',
    appId: '1:286957351892:web:e3be95a533830c5a649c41',
    messagingSenderId: '286957351892',
    projectId: 'chat-with-firebase-83b97',
    authDomain: 'chat-with-firebase-83b97.firebaseapp.com',
    storageBucket: 'chat-with-firebase-83b97.appspot.com',
    measurementId: 'G-0NWJFYD6QS',
  );

}